version: '3'
services:
  web:
    build: . #build utiliza o Dockerfile
    volumes:
      - ./ ........... : ..........
    ports:
      - 8080:80
  outro_server:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 33060:3306
    volumes:
      - ./............ : ...........
